using System.Collections.Concurrent;
using kartlegging_websocket_prosjekt_backend.Interfaces;
namespace kartlegging_websocket_prosjekt_backend.Models;

public class NameHandler : INameHandler
{
    private readonly ConcurrentDictionary<string, string> _userNameAndDisplayNameOverview = [];
    private readonly ConcurrentDictionary<string, int> _userNameActivityOverview = [];
    private readonly string[] _adjectives =
    [ // Common descriptive adjectives
        "abandoned", "able", "absolute", "adorable", "adventurous", "academic", "acceptable",
        "acclaimed", "accomplished", "accurate", "aching", "acidic", "acrobatic", "active",
        "actual", "adept", "admirable", "admired", "adolescent", "adorable", "adored",
        "advanced", "afraid", "affectionate", "aged", "aggravating", "aggressive", "agile",
        "agitated", "agonizing", "agreeable", "alarmed", "alarming", "alert", "alienated",
        "alive", "all", "altruistic", "amazing", "ambitious", "ample", "amused", "amusing",
        "anchored", "ancient", "angelic", "angry", "anguished", "animated", "annual",
        "another", "antique", "anxious", "apprehensive", "appropriate", "apt", "arctic",
        "arid", "aromatic", "artistic", "ashamed", "assured", "astonishing", "athletic",
        "attached", "attentive", "attractive", "austere", "authentic", "authorized",
        "automatic", "avaricious", "average", "aware", "awesome", "awful",

        // B adjectives
        "babyish", "bad", "back", "baggy", "bare", "barren", "basic", "beautiful",
        "belated", "beloved", "beneficial", "better", "best", "bewitched", "big",
        "big-hearted", "biodegradable", "bite-sized", "bitter", "black", "black-and-white",
        "bland", "blank", "blaring", "bleak", "blind", "blissful", "blond", "blue",
        "blushing", "bogus", "boiling", "bold", "bony", "boring", "bossy", "both",
        "bouncy", "bountiful", "bowed", "brave", "breakable", "brief", "bright",
        "brilliant", "brisk", "broken", "bronze", "brown", "bruised", "bubbly", "bulky",
        "bumpy", "buoyant", "burdensome", "burly", "bustling", "busy", "buttery",

        // C adjectives
        "calm", "candid", "canine", "capital", "carefree", "careful", "careless",
        "caring", "cautious", "cavernous", "celebrated", "charming", "cheap", "cheerful",
        "cheery", "chief", "chilly", "chubby", "circular", "classic", "clean", "clear",
        "clear-cut", "clever", "close", "closed", "cloudy", "clueless", "clumsy",
        "cluttered", "coarse", "cold", "colorful", "colorless", "colossal", "comfortable",
        "common", "compassionate", "competent", "complete", "complex", "complicated",
        "composed", "concerned", "concrete", "confused", "conscious", "considerate",
        "constant", "content", "conventional", "cooked", "cool", "cooperative",
        "coordinated", "corny", "corrupt", "costly", "courageous", "courteous", "crafty",
        "crazy", "creamy", "creative", "creepy", "criminal", "crisp", "critical",
        "crooked", "crowded", "cruel", "crushing", "cuddly", "cultivated", "cultured",
        "cumbersome", "curly", "curvy", "cute", "cylindrical",

        // D adjectives
        "damaged", "damp", "dangerous", "dapper", "daring", "darling", "dark", "dazzling",
        "dead", "deadly", "deafening", "dear", "dearest", "decent", "decimal", "decisive",
        "deep", "defenseless", "defensive", "defiant", "deficient", "definite", "definitive",
        "delayed", "delectable", "delicious", "delightful", "delirious", "demanding",
        "dense", "dental", "dependable", "dependent", "descriptive", "deserted", "detailed",
        "determined", "devoted", "different", "difficult", "digital", "diligent", "dim",
        "dimpled", "dimwitted", "direct", "disastrous", "discrete", "disfigured",
        "disgusting", "disloyal", "dismal", "distant", "downright", "dreary", "dirty",
        "disguised", "dishonest", "dismal", "distant", "distinct", "distorted", "dizzy",
        "dopey", "doting", "double", "downright", "drab", "drafty", "dramatic", "dreary",
        "droopy", "dry", "dual", "dull", "dutiful", "dynamic",

        // E adjectives
        "eager", "earnest", "early", "easy", "easy-going", "ecstatic", "edible", "educated",
        "elaborate", "elastic", "elated", "elderly", "electric", "elegant", "elementary",
        "elliptical", "embarrassed", "embellished", "eminent", "emotional", "empty",
        "enchanted", "enchanting", "energetic", "enlightened", "enormous", "enraged",
        "entire", "envious", "equal", "equatorial", "essential", "esteemed", "ethical",
        "euphoric", "even", "evergreen", "everlasting", "every", "evil", "exalted",
        "excellent", "exemplary", "exhausted", "excitable", "excited", "exciting",
        "exotic", "expensive", "experienced", "expert", "extraneous", "extroverted",
        "extra-large", "extra-small", "fabulous", "failing", "faint", "fair", "faithful",

        // F adjectives
        "fake", "false", "familiar", "famous", "fancy", "fantastic", "far", "faraway",
        "far-flung", "far-off", "fast", "fat", "fatal", "fatherly", "favorable",
        "favorite", "fearful", "fearless", "feisty", "feline", "female", "feminine",
        "few", "fickle", "filthy", "fine", "finished", "firm", "first", "firsthand",
        "fitting", "fixed", "flaky", "flamboyant", "flashy", "flat", "flawed", "flawless",
        "flickering", "flimsy", "flippant", "flowery", "fluffy", "fluid", "flustered",
        "focused", "fond", "foolhardy", "foolish", "forceful", "forked", "formal",
        "forsaken", "forthright", "fortunate", "fragrant", "frail", "frank", "frayed",
        "free", "French", "fresh", "frequent", "friendly", "frightened", "frightening",
        "frigid", "frilly", "frizzy", "frivolous", "front", "frosty", "frozen", "frugal",
        "fruitful", "full", "fumbling", "functional", "funny", "fussy", "fuzzy",

        // G adjectives
        "gargantuan", "gaseous", "general", "generous", "gentle", "genuine", "giant",
        "giddy", "gigantic", "gifted", "giving", "glamorous", "glaring", "glass", "gleaming",
        "gleeful", "glistening", "glittering", "gloomy", "glorious", "glossy", "glum",
        "golden", "good", "good-natured", "gorgeous", "graceful", "gracious", "grand",
        "grandiose", "granular", "grateful", "grave", "gray", "great", "greedy", "green",
        "gregarious", "grim", "grimy", "gripping", "grizzled", "grouchy", "grounded",
        "growing", "growling", "grown", "grubby", "gruesome", "grumpy", "guilty", "gullible",
        "gummy",

        // H adjectives
        "hairy", "half", "handmade", "handsome", "handy", "happy", "happy-go-lucky",
        "hard", "hard-to-find", "harmful", "harmless", "harmonious", "harsh", "hasty",
        "hateful", "haunting", "healthy", "heartfelt", "hearty", "heavenly", "heavy",
        "hefty", "helpful", "helpless", "hidden", "hideous", "high", "high-level",
        "hilarious", "hoarse", "hollow", "homely", "honest", "honorable", "honored",
        "hopeful", "horrible", "hospitable", "hot", "huge", "humble", "humiliating",
        "humming", "humongous", "hungry", "hurtful", "hushed", "husky", "hypnotic",

        // I adjectives
        "icy", "ideal", "idealistic", "identical", "idle", "idiotic", "idolized",
        "ignorant", "ill", "illegal", "ill-fated", "ill-informed", "illiterate", "illustrious",
        "imaginary", "imaginative", "immaculate", "immaterial", "immediate", "immense",
        "impassioned", "impeccable", "impartial", "imperfect", "imperturbable", "impish",
        "impolite", "important", "impossible", "impractical", "impressionable", "impressive",
        "improbable", "impure", "inborn", "incomparable", "incompatible", "incomplete",
        "inconsequential", "incredible", "indelible", "inexperienced", "indolent", "infamous",
        "infantile", "infatuated", "inferior", "infinite", "informal", "innocent", "insecure",
        "insidious", "insignificant", "insistent", "instructive", "insubstantial", "intelligent",
        "intent", "intentional", "interesting", "internal", "international", "intrepid",
        "ironclad", "irresponsible", "irritating", "itchy",

        // J adjectives
        "jaded", "jagged", "jam-packed", "jaunty", "jealous", "jittery", "joint", "jolly",
        "jovial", "joyful", "joyous", "jubilant", "judicious", "juicy", "jumbo", "junior",
        "jumpy", "juvenile",

        // K adjectives
        "kaleidoscopic", "keen", "key", "kind", "kindhearted", "kindly", "klutzy", "knobby",
        "knotty", "knowledgeable", "knowing", "known", "kooky", "kosher",

        // L adjectives
        "lame", "lanky", "large", "last", "lasting", "late", "lavish", "lawful", "lazy",
        "leading", "lean", "leafy", "left", "legal", "legitimate", "light", "lighthearted",
        "likable", "likely", "limited", "limp", "limping", "linear", "lined", "liquid",
        "little", "live", "lively", "livid", "loathsome", "lone", "lonely", "long",
        "long-term", "loose", "lopsided", "lost", "loud", "lovable", "lovely", "loving",
        "low", "loyal", "lucky", "lumbering", "luminous", "lumpy", "lustrous", "luxurious",

        // M adjectives
        "mad", "magnificent", "majestic", "major", "male", "mammoth", "married", "marvelous",
        "masculine", "massive", "mature", "meager", "mealy", "mean", "measly", "meaty",
        "medical", "mediocre", "medium", "meek", "mellow", "melodic", "memorable", "menacing",
        "merry", "messy", "metallic", "mild", "milky", "mindless", "miniature", "minor",
        "minty", "miserable", "miserly", "misguided", "misty", "mixed", "modern", "modest",
        "moist", "monstrous", "monthly", "monumental", "moral", "mortified", "motherly",
        "motionless", "mountainous", "muddy", "muffled", "multicolored", "mundane", "murky",
        "mushy", "musty", "muted", "mysterious",

        // N adjectives
        "naive", "narrow", "nasty", "natural", "naughty", "nautical", "near", "neat", "necessary",
        "needy", "negative", "neglected", "negligible", "neighboring", "nervous", "new",
        "next", "nice", "nifty", "nimble", "nippy", "nocturnal", "noisy", "nonstop",
        "normal", "notable", "noted", "noteworthy", "novel", "noxious", "numb", "nutritious",
        "nutty",

        // O adjectives
        "obedient", "obese", "oblong", "oily", "oblong", "obvious", "occasional", "odd",
        "oddball", "offbeat", "offensive", "official", "old", "old-fashioned", "only",
        "open", "optimal", "optimistic", "opulent", "orange", "orderly", "organic",
        "ornate", "ornery", "ordinary", "original", "other", "our", "outlying", "outgoing",
        "outlandish", "outrageous", "outstanding", "oval", "overcooked", "overdue", "overjoyed",
        "overlooked", "palatable", "pale", "paltry", "parallel", "parched", "partial",
        "passionate", "past", "pastel", "peaceful", "peppery", "perfect", "perfumed",

        // P adjectives
        "periodic", "perky", "personal", "pertinent", "pesky", "pessimistic", "petty",
        "phony", "physical", "piercing", "pink", "pitiful", "plain", "plaintive", "plastic",
        "playful", "pleasant", "pleased", "pleasing", "plump", "plush", "polished", "polite",
        "political", "pointed", "pointless", "poised", "poor", "popular", "portly", "posh",
        "positive", "possible", "potable", "powerful", "powerless", "practical", "precious",
        "present", "prestigious", "pretty", "precious", "previous", "pricey", "prickly",
        "primary", "prime", "pristine", "private", "prize", "probable", "productive",
        "profitable", "profuse", "proper", "proud", "prudent", "punctual", "pungent", "puny",
        "pure", "purple", "pushy", "putrid", "puzzled", "puzzling",

        // Q adjectives
        "quaint", "qualified", "quarrelsome", "quarterly", "queasy", "querulous", "questionable",
        "quick", "quick-witted", "quiet", "quintessential", "quirky", "quixotic", "quizzical",

        // R adjectives
        "radiant", "ragged", "rapid", "rare", "rash", "raw", "recent", "reckless", "rectangular",
        "ready", "real", "realistic", "reasonable", "red", "reflecting", "regal", "regular",
        "reliable", "relieved", "remarkable", "remorseful", "remote", "repentant", "required",
        "respectful", "responsible", "repulsive", "revolving", "rewarding", "rich", "rigid",
        "right", "ringed", "ripe", "roasted", "robust", "rosy", "rotating", "rotten", "rough",
        "round", "rowdy", "royal", "rubbery", "ruddy", "rude", "rundown", "runny", "rural",
        "rusty", "ruthless",

        // S adjectives
        "sad", "safe", "salty", "same", "sandy", "sane", "sarcastic", "sardonic", "satisfied",
        "savory", "scaly", "scarce", "scared", "scary", "scented", "scholarly", "scientific",
        "scornful", "scratchy", "scrawny", "second", "secondary", "second-hand", "secret",
        "self-assured", "self-reliant", "selfish", "sentimental", "separate", "serene",
        "serious", "serpentine", "several", "severe", "shabby", "shadowy", "shady",
        "shallow", "shameful", "shameless", "sharp", "shimmering", "shiny", "shocked",
        "shocking", "shoddy", "short", "short-term", "showy", "shrill", "shy", "sick",
        "silent", "silky", "silly", "silver", "similar", "simple", "simplistic", "sinful",
        "single", "sizzling", "skeletal", "skinny", "sleepy", "slight", "slim", "slimy",
        "slippery", "slow", "slushy", "small", "smart", "smoggy", "smooth", "smug", "snappy",
        "snarling", "sneaky", "sniveling", "snoopy", "sociable", "soft", "soggy", "solid",
        "somber", "some", "spherical", "sophisticated", "sore", "sorrowful", "soulful",
        "soupy", "sour", "Spanish", "sparkling", "sparse", "specific", "spectacular", "speedy",
        "spicy", "spiffy", "spirited", "spiteful", "splendid", "spotless", "spotted", "spry",
        "square", "squeaky", "squiggly", "stable", "staid", "stained", "stale", "standard",
        "starchy", "stark", "starry", "steep", "sticky", "stiff", "stimulating", "stingy",
        "stormy", "straight", "strange", "steel", "strict", "strident", "striking", "striped",
        "strong", "studious", "stunning", "stupendous", "stupid", "sturdy", "stylish",
        "subdued", "submissive", "substantial", "subtle", "suburban", "sudden", "sugary",
        "sunny", "super", "superb", "superficial", "superior", "supportive", "sure-footed",
        "surprised", "suspicious", "svelte", "sweaty", "sweet", "sweltering", "swift", "sympathetic",
        "tall", "talkative", "tame", "tan", "tangible", "tart", "tasty", "tattered", "taut",

        // T adjectives
        "tedious", "teeming", "tempting", "tender", "tense", "tepid", "terrible", "terrific",
        "testy", "thankful", "that", "these", "thick", "thin", "third", "thirsty", "this",
        "thorough", "thorny", "those", "thoughtful", "threadbare", "thrifty", "thunderous",
        "tidy", "tight", "timely", "tinted", "tiny", "tired", "torn", "total", "tough",
        "traumatic", "treasured", "tremendous", "tragic", "trained", "tremendous", "triangular",
        "tricky", "trifling", "trim", "trivial", "troubled", "true", "trusting", "trustworthy",
        "trusty", "truthful", "tubby", "turbulent", "twin", "typical",

        // U adjectives
        "ugly", "ultimate", "unacceptable", "unaware", "uncomfortable", "uncommon", "unconscious",
        "understated", "unequaled", "uneven", "unfinished", "unfit", "unfolded", "unfortunate",
        "unhappy", "unhealthy", "uniform", "unimportant", "unique", "united", "unkempt",
        "unknown", "unlawful", "unlined", "unlucky", "unnatural", "unpleasant", "unrealistic",
        "unripe", "unruly", "unselfish", "unsightly", "unsteady", "unsung", "untidy", "untimely",
        "untried", "untrue", "unused", "unusual", "unwelcome", "unwieldy", "unwilling", "unwitting",
        "unwritten", "upbeat", "upright", "upset", "urban", "usable", "used", "useful", "useless",
        "utilized", "utter",

        // V adjectives
        "vacant", "vague", "vain", "valid", "valuable", "vapid", "variable", "vast", "velvety",
        "venerated", "vengeful", "verifiable", "vibrant", "vicious", "victorious", "vigilant",
        "vigorous", "villainous", "violet", "violent", "virtual", "virtuous", "visible",
        "vital", "vivacious", "vivid", "voluminous",

        // W adjectives
        "wan", "warlike", "warm", "warmhearted", "warped", "wary", "wasteful", "watchful",
        "waterlogged", "watery", "wavy", "wealthy", "weak", "weary", "webbed", "wee", "weekly",
        "weepy", "weighty", "weird", "welcome", "well-documented", "well-groomed", "well-informed",
        "well-lit", "well-made", "well-off", "well-to-do", "well-worn", "wet", "which", "whimsical",
        "whirlwind", "whispered", "white", "whole", "whopping", "wicked", "wide", "wide-eyed",
        "wiggly", "wild", "willing", "wilted", "winding", "windy", "winged", "wiry", "wise",
        "witty", "wobbly", "woeful", "wonderful", "wooden", "woozy", "wordy", "worldly",
        "worn", "worried", "worrisome", "worse", "worst", "worthless", "worthwhile", "worthy",
        "wrathful", "wretched", "writhing", "wrong", "wry",

        // X adjectives
        "xenophobic", "xeric",

        // Y adjectives
        "yearly", "yellow", "yellowish", "young", "youthful", "yummy",

        // Z adjectives
        "zany", "zealous", "zesty", "zigzag", "zippy", "zonked"
    ];

    private readonly string[] _nouns =
    [
        // People and roles
        "actor", "adult", "agent", "artist", "assistant", "athlete", "author", "baker",
        "banker", "barber", "builder", "businessman", "businesswoman", "butcher", "carpenter",
        "cashier", "chef", "child", "citizen", "cleaner", "clerk", "coach", "collector",
        "composer", "conductor", "consultant", "contractor", "cook", "counselor", "craftsman",
        "creator", "critic", "customer", "dancer", "dealer", "decorator", "dentist", "designer",
        "detective", "diplomat", "director", "doctor", "driver", "economist", "editor",
        "educator", "electrician", "employee", "employer", "engineer", "entertainer",
        "entrepreneur", "executive", "expert", "explorer", "farmer", "firefighter", "fisherman",
        "florist", "gardener", "hairdresser", "historian", "hunter", "inspector", "instructor",
        "interpreter", "inventor", "investigator", "janitor", "jeweler", "journalist", "judge",
        "laborer", "lawyer", "lecturer", "librarian", "lifeguard", "magician", "manager",
        "manufacturer", "mechanic", "mentor", "merchant", "messenger", "musician", "novelist",
        "nurse", "observer", "officer", "operator", "painter", "passenger", "performer",
        "pharmacist", "photographer", "physician", "pilot", "plumber", "poet", "politician",
        "porter", "presenter", "president", "producer", "professor", "programmer", "psychologist",
        "publisher", "receptionist", "reporter", "researcher", "retailer", "sailor", "salesperson",
        "scholar", "scientist", "secretary", "servant", "singer", "soldier", "speaker", "specialist",
        "student", "stylist", "supervisor", "surgeon", "surveyor", "teacher", "technician",
        "therapist", "tourist", "trainer", "translator", "traveler", "tutor", "writer",

        // Animals
        "alligator", "ant", "ape", "badger", "bat", "bear", "beaver", "bee", "beetle", "bird",
        "buffalo", "butterfly", "camel", "cat", "caterpillar", "chicken", "chimpanzee", "cow",
        "coyote", "crab", "cricket", "crocodile", "crow", "deer", "dog", "dolphin", "donkey",
        "dove", "duck", "eagle", "elephant", "elk", "falcon", "ferret", "finch", "fish", "flamingo",
        "fly", "fox", "frog", "gazelle", "giraffe", "goat", "goldfish", "goose", "gorilla",
        "grasshopper", "hamster", "hawk", "hedgehog", "heron", "horse", "hummingbird", "hyena",
        "impala", "jaguar", "jellyfish", "kangaroo", "koala", "leopard", "lion", "lizard", "llama",
        "lobster", "monkey", "moose", "mosquito", "moth", "mouse", "mule", "octopus", "ostrich",
        "otter", "owl", "ox", "oyster", "panda", "panther", "parrot", "peacock", "pelican",
        "penguin", "pheasant", "pig", "pigeon", "pony", "porcupine", "porpoise", "quail", "rabbit",
        "raccoon", "ram", "rat", "raven", "reindeer", "rhinoceros", "robin", "rooster", "salamander",
        "salmon", "scorpion", "seal", "shark", "sheep", "skunk", "sloth", "snail", "snake", "sparrow",
        "spider", "squid", "squirrel", "starling", "stork", "swallow", "swan", "tiger", "toad",
        "tortoise", "toucan", "trout", "turkey", "turtle", "vulture", "walrus", "wasp", "weasel",
        "whale", "wolf", "wolverine", "woodpecker", "worm", "zebra",

        // Physical objects
        "album", "anchor", "anvil", "apparatus", "appliance", "arch", "arrow", "artifact",
        "badge", "bag", "ball", "balloon", "banner", "barrel", "basket", "battery", "beacon",
        "beam", "bell", "blanket", "block", "board", "boat", "bolt", "bomb", "book", "bottle",
        "bowl", "box", "bracelet", "brake", "brick", "bridge", "brush", "bucket", "bulb", "bullet",
        "button", "cabinet", "cage", "cake", "calculator", "calendar", "camera", "candle", "cannon",
        "canvas", "cap", "cape", "car", "card", "carpet", "carriage", "cart", "case", "cassette",
        "castle", "catalog", "chain", "chair", "chalk", "charger", "chart", "chisel", "clock",
        "cloth", "cloud", "clover", "club", "coat", "coffee", "coin", "collar", "comb", "compass",
        "computer", "container", "contraption", "cord", "couch", "counter", "cradle", "crane",
        "crate", "crown", "cube", "cup", "curtain", "cushion", "cylinder", "dart", "dashboard",
        "decoration", "desk", "device", "diamond", "diary", "dice", "dictionary", "disc", "dish",
        "display", "document", "drawer", "dress", "drill", "drink", "drum", "dryer", "earring",
        "easel", "egg", "engine", "envelope", "eraser", "fabric", "fan", "feather", "fence",
        "file", "film", "filter", "flag", "flashlight", "flask", "flute", "folder", "food",
        "fork", "fountain", "frame", "freezer", "fruit", "funnel", "furnace", "furniture",
        "gadget", "game", "garage", "garbage", "garden", "garment", "gas", "gate", "gauge",
        "gear", "gem", "gift", "glass", "glasses", "glove", "glue", "guitar", "gun", "hammer",
        "handle", "hanger", "hat", "headset", "helmet", "hook", "horn", "hose", "hub", "ice",
        "instrument", "iron", "jacket", "jar", "jeans", "jewel", "journal", "jug", "kettle",
        "key", "keyboard", "knife", "knob", "ladder", "lamp", "lantern", "laptop", "latch",
        "lens", "lever", "light", "lock", "locker", "locket", "machine", "magazine", "magnet",
        "magnifier", "map", "marker", "mask", "mat", "match", "mattress", "medal", "microphone",
        "microscope", "mirror", "missile", "mitten", "mixer", "mobile", "monitor", "mop",
        "motor", "motorcycle", "mould", "mug", "nail", "napkin", "necklace", "needle", "nest",
        "newspaper", "notebook", "novel", "nozzle", "nut", "oar", "oven", "package", "pad",
        "paddle", "padlock", "page", "pail", "pan", "paper", "parachute", "parcel", "pendant",
        "pencil", "pendulum", "pen", "phone", "photograph", "piano", "picture", "pillow", "pipe",
        "pistol", "pitcher", "plane", "planet", "plate", "platform", "pot", "projector", "pulley",
        "pump", "purse", "puzzle", "quilt", "rack", "racket", "radio", "raft", "rag", "rail",
        "rake", "ramp", "razor", "record", "remote", "rifle", "ring", "robot", "rock", "rocket",
        "rod", "roller", "roof", "rope", "rug", "ruler", "saddle", "safe", "sail", "salt",
        "sandal", "satellite", "sauce", "scale", "scanner", "scarf", "scissors", "screen",
        "screw", "sculpture", "seal", "seat", "shield", "ship", "shirt", "shoe", "shovel",
        "sign", "silk", "sink", "siren", "skateboard", "ski", "skirt", "sled", "soap", "socket",
        "sofa", "spring", "spoon", "spotlight", "stage", "stamp", "stapler", "statue", "stereo",
        "stick", "stool", "stove", "strap", "string", "submarine", "sugar", "suit", "suitcase",
        "sunglasses", "sweater", "switch", "sword", "system", "table", "tablet", "tag", "tank",
        "tape", "telephone", "telescope", "television", "tent", "thermometer", "thread", "throne",
        "ticket", "tie", "tile", "timer", "toaster", "toilet", "tool", "toothbrush", "towel", "toy",
        "tractor", "train", "tray", "treasure", "tree", "trophy", "truck", "tube", "typewriter",
        "umbrella", "uniform", "vacuum", "valve", "vase", "vault", "vehicle", "vest", "video",
        "wallet", "watch", "weapon", "wheel", "whip", "whistle", "window", "wire", "wrench", "yoke",
        "zipper",

        // Places and Locations
        "abbey", "academy", "airport", "alley", "apartment", "arcade", "arena", "avenue", "bakery",
        "balcony", "bank", "bar", "barn", "basement", "bay", "beach", "brewery", "bridge", "building",
        "bungalow", "bunker", "cabin", "cafe", "cafeteria", "camp", "campus", "canal", "canyon",
        "castle", "cathedral", "cave", "cemetery", "chapel", "church", "cinema", "city", "classroom",
        "clinic", "club", "coast", "college", "colony", "continent", "cottage", "country", "courthouse",
        "cove", "crater", "creek", "desert", "dock", "dormitory", "embassy", "empire", "factory",
        "farm", "field", "forest", "fort", "fortress", "gallery", "garden", "garage", "glacier",
        "greenhouse", "gymnasium", "hall", "harbor", "headquarters", "hideaway", "highway", "hill",
        "hospital", "hotel", "house", "hub", "hut", "inn", "institution", "island", "jail", "jungle",
        "kingdom", "kitchen", "laboratory", "lake", "land", "landmark", "landscape", "library",
        "lighthouse", "lodge", "lounge", "mall", "mansion", "marina", "market", "meadow", "monastery",
        "monument", "mosque", "mountain", "museum", "nation", "neighborhood", "nest", "observatory",
        "ocean", "office", "oasis", "palace", "park", "pasture", "path", "patio", "pavilion", "pier",
        "plaza", "pond", "pool", "port", "prison", "province", "pub", "pueblo", "quarry", "ranch",
        "reef", "region", "reserve", "residence", "restaurant", "retreat", "river", "road", "room",
        "ruin", "sanctuary", "school", "sea", "settlement", "shelter", "shop", "shore", "shrine",
        "sidewalk", "skyscraper", "spa", "stadium", "station", "store", "street", "studio", "suburb",
        "summit", "swamp", "tavern", "temple", "terminal", "terrace", "territory", "theater", "tower",
        "town", "trail", "train", "tunnel", "university", "valley", "village", "vineyard", "volcano",
        "warehouse", "waterfall", "wilderness", "workshop", "zoo",

        // Abstract concepts
        "ability", "absence", "abundance", "acceptance", "accessibility", "accomplishment",
        "accountability", "accuracy", "achievement", "action", "adaptability", "addition", "adequacy",
        "adjustment", "admiration", "adoption", "advance", "advantage", "adventure", "advice",
        "advocacy", "affection", "affinity", "age", "agenda", "aggression", "agility", "agreement",
        "aid", "aim", "alertness", "allegiance", "alliance", "allowance", "alternative", "ambiguity",
        "ambition", "amendment", "amusement", "analysis", "ancestry", "anger", "angle", "animation",
        "anniversary", "announcement", "answer", "anticipation", "anxiety", "apology", "appeal",
        "appearance", "appetite", "applause", "application", "appointment", "appreciation", "approach",
        "approval", "aptitude", "area", "argument", "arithmetic", "arrangement", "arrival", "art",
        "article", "artifice", "ascent", "aspect", "aspiration", "assault", "assembly", "assertion",
        "assessment", "assignment", "assistance", "assumption", "assurance", "attachment", "attack",
        "attainment", "attempt", "attention", "attitude", "attraction", "attribute", "auction",
        "audience", "authority", "autonomy", "availability", "aversion", "awareness", "awe",
        "background", "balance", "bargain", "barrier", "base", "basis", "battle", "beauty",
        "beginning", "behavior", "belief", "belonging", "benefit", "benevolence", "bias", "biology",
        "blame", "blessing", "bliss", "bond", "bonus", "border", "boredom", "boundary", "bravery",
        "breach", "breakdown", "breakthrough", "breeding", "brevity", "brotherhood", "budget",
        "burden", "bureaucracy", "business", "bystander", "calculation", "call", "campaign",
        "capacity", "capital", "care", "career", "caution", "celebration", "censorship", "ceremony",
        "certainty", "certificate", "challenge", "chance", "change", "chaos", "character", "charge",
        "charity", "charm", "chase", "chemistry", "choice", "circulation", "circumstance", "citizenship",
        "civilization", "claim", "clarity", "class", "classification", "clause", "clearance", "climate",
        "closure", "coalition", "code", "cognition", "coincidence", "collaboration", "collection",
        "collision", "combination", "comfort", "command", "commerce", "commission", "commitment",
        "committee", "commodity", "communication", "community", "company", "compassion", "compensation",
        "competence", "competition", "complaint", "complexity", "compliance", "complication", "component",
        "composition", "compromise", "compulsion", "computation", "concept", "conception", "concern",
        "concession", "conclusion", "condition", "conduct", "conference", "confidence", "configuration",
        "confirmation", "conflict", "conformity", "confusion", "congratulation", "conjunction",
        "connection", "consensus", "consent", "consequence", "conservation", "consideration",
        "consistency", "conspiracy", "constant", "constitution", "constraint", "construction",
        "consultation", "consumption", "contact", "contemplation", "contempt", "content", "contention",
        "context", "contingency", "continuity", "contract", "contradiction", "contrast", "contribution",
        "control", "controversy", "convenience", "convention", "conversation", "conversion", "conviction",
        "cooperation", "coordination", "copy", "core", "corporation", "correlation", "correspondence",
        "corruption", "cost", "counsel", "count", "counterpart", "coup", "courage", "course", "courtesy",
        "coverage", "craft", "creation", "credential", "credit", "creed", "crisis", "criterion",
        "criticism", "critique", "cross", "crowd", "cruelty", "cult", "culture", "currency", "current",
        "custody", "custom", "cycle", "damage", "danger", "data", "date", "dawn", "deal", "debate",
        "debt", "debut", "deceit", "decision", "declaration", "decline", "decoration", "decrease",
        "dedication", "deed", "default", "defeat", "defect", "defense", "deficiency", "deficit",
        "definition", "degree", "delay", "delegation", "delight", "delivery", "demand", "democracy",
        "denial", "density", "department", "departure", "dependence", "deposit", "depression", "depth",
        "derivation", "descendant", "description", "design", "designation", "desire", "despair",
        "destination", "destiny", "destruction", "detail", "detection", "determination", "development",
        "deviation", "device", "devotion", "diagnosis", "dialogue", "difference", "difficulty",
        "dignity", "dilemma", "dimension", "direction", "disability", "disadvantage", "disagreement",
        "disappearance", "disaster", "discipline", "disclosure", "discontinuity", "discount", "discovery",
        "discretion", "discrimination", "discussion", "disease", "disgrace", "disgust", "dishonesty",
        "dismissal", "disorder", "disparity", "dispatch", "displacement", "display", "disposal",
        "disposition", "dispute", "disruption", "dissent", "distance", "distinction", "distortion",
        "distraction", "distribution", "distrust", "disturbance", "diversity", "division", "doctrine",
        "document", "dominance", "donation", "dose", "doubt", "draft", "drama", "dream", "drift",
        "drive", "duration", "duty", "dynamics", "eagerness", "earnestness", "ease", "ecology",
        "economics", "economy", "ecstasy", "edge", "edition", "education", "effect", "effectiveness",
        "efficiency", "effort", "ego", "elaboration", "elation", "election", "element", "elevation",
        "eligibility", "elimination", "embarrassment", "emergence", "emotion", "emphasis", "empire",
        "employment", "encouragement", "end", "endeavor", "endurance", "enemy", "energy", "enforcement",
        "engagement", "enhancement", "enjoyment", "enlightenment", "enthusiasm", "entity", "entrance",
        "entry", "environment", "envy", "episode", "equality", "equilibrium", "equity", "equivalent",
        "era", "error", "escape", "essence", "establishment", "estate", "estimate", "ethics", "evaluation",
        "event", "evidence", "evolution", "exaggeration", "examination", "example", "excellence",
        "exception", "excess", "exchange", "excitement", "exclusion", "excuse", "execution", "exercise",
        "exhaustion", "existence", "exit", "expansion", "expectation", "expedition", "expenditure",
        "expense", "experience", "experiment", "explanation", "exploration", "exposure", "expression",
        "extension", "extent", "extract", "extremity", "fabric", "facade", "face", "facility", "fact",
        "faction", "factor", "faculty", "failure", "fairness", "faith", "fallacy", "falsehood", "fame",
        "familiarity", "family", "fantasy", "fashion", "fate", "fatigue", "fault", "favor", "fear",
        "feasibility", "feature", "feedback", "feeling", "fellowship", "fervor", "fiction", "field",
        "fight", "figure", "flaw", "flexibility", "flight", "flow", "fluctuation", "focus", "folly",
        "fondness", "force", "forecast", "forethought", "forgiveness", "form", "formation", "formula",
        "fortitude", "fortune", "foundation", "fragility", "fragment", "framework", "franchise",
        "fraud", "freedom", "frequency", "freshness", "friendship", "front", "frustration", "function",
        "fund", "funding", "fury", "future", "gain", "game", "gap", "gender", "generalization",
        "generation", "generosity", "genius", "genre", "gesture", "gift", "glamour", "glimpse", "goal",
        "governance", "government", "grace", "grade", "grandeur", "grant", "graph", "grasp", "gratitude",
        "gravity", "greatness", "greed", "grief", "grievance", "ground", "group", "growth", "guarantee",
        "guardianship", "guess", "guidance", "guideline", "guilt", "habit", "habitat", "hair", "half",
        "halt", "handicap", "handling", "happiness", "harassment", "hardship", "harm", "harmony",
        "harvest", "hate", "hatred", "hazard", "heading", "health", "heart", "heat", "height", "heir",
        "help", "heritage", "hesitation", "hierarchy", "highlight", "hinduism", "hint", "history",
        "honesty", "honor", "hope", "horizon", "horror", "hospitality", "host", "hostility", "hour",
        "household", "housing", "humanity", "humility", "humor", "hunger", "hurt", "hypothesis", "idea",
        "ideal", "identity", "ideology", "idiosyncrasy", "ignorance", "illusion", "image", "imagination",
        "imbalance", "imitation", "immediacy", "immensity", "immunity", "impact", "impartiality",
        "impediment", "imperative", "implementation", "implication", "importance", "impossibility",
        "impression", "imprisonment", "improvement", "impulse", "inability", "inaccuracy", "incentive",
        "inception", "incident", "inclination", "inclusion", "income", "incompatibility", "inconsistency",
        "inconvenience", "increase", "independence", "indication", "indifference", "indignation",
        "individual", "industry", "inequality", "inevitability", "infancy", "inference", "inferiority",
        "inflation", "influence", "information", "infrastructure", "ingredient", "inheritance",
        "inhibition", "initiative", "injury", "injustice", "innocence", "innovation", "input", "inquiry",
        "insecurity", "insight", "insistence", "inspection", "inspiration", "installation", "instance",
        "instinct", "institution", "instruction", "instrument", "insufficiency", "insurance", "intake",
        "integrity", "intellect", "intelligence", "intensity", "intent", "intention", "interaction",
        "interest", "interface", "interference", "interim", "interpretation", "intervention", "interview",
        "intimacy", "introduction", "intuition", "invasion", "invention", "investigation", "investment",
        "invitation", "involvement", "irony", "irregularity", "isolation", "issue", "item", "jersey",
        "joint", "joke", "journey", "joy", "judgment", "jump", "juncture", "jungle", "jurisdiction",
        "justice", "justification", "kind", "kindness", "kinship", "knowledge", "label", "labor",
        "lack", "land", "landscape", "language", "lapse", "latitude", "latter", "laughter", "launch",
        "law", "layer", "leadership", "learning", "lease", "leave", "legacy", "legend", "legislation",
        "legitimacy", "leisure", "length", "lesson", "level", "liability", "liaison", "liberty",
        "license", "lie", "life", "lifetime", "likelihood", "limit", "limitation", "line", "link",
        "liquidation", "list", "literature", "litigation", "load", "loan", "location", "logic",
        "loneliness", "longevity", "look", "loop", "loss", "love", "loyalty", "luck", "luxury",
        "majority", "makeup", "management", "mandate", "manifestation", "manipulation", "manner",
        "manufacturing", "margin", "mark", "market", "marriage", "mass", "mastery", "match",
        "material", "materialization", "mathematics", "matter", "maturity", "maximum", "meaning",
        "means", "measure", "measurement", "mechanism", "media", "mediation", "medicine", "medium",
        "meeting", "melody", "member", "membership", "memory", "mention", "menu", "mercy", "merger",
        "merit", "message", "metaphor", "method", "methodology", "middle", "migration", "militancy",
        "mind", "minimum", "ministry", "minority", "minute", "miracle", "misery", "mission", "mistake",
        "mistrust", "mobilization", "mode", "model", "moderation", "modernization", "modification",
        "module", "moment", "momentum", "money", "monopoly", "mood", "morality", "morning", "motive",
        "movement", "multitude", "murder", "muscle", "music", "mutation", "mystery", "myth", "name",
        "narrative", "nation", "nature", "navigation", "necessity", "need", "negligence", "negotiation",
        "neighborhood", "network", "neutrality", "news", "nightmare", "nobility", "node", "noise",
        "norm", "normalcy", "north", "notation", "note", "notion", "novelty", "number", "nutrition",
        "oath", "obedience", "objection", "objective", "obligation", "observation", "obsession",
        "obstacle", "occasion", "occupation", "occurrence", "odds", "odor", "offense", "offer", "office",
        "officer", "official", "omission", "opening", "operation", "opinion", "opportunity", "opposition",
        "optimism", "option", "order", "ordinary", "org", "organization", "orientation", "origin",
        "other", "outbreak", "outcome", "outfit", "outlet", "output", "outset", "outside", "overlap",
        "oversight", "ownership", "pace", "pack", "package", "page", "pain", "pair", "panel", "panic",
        "paper", "paradigm", "paradox", "paragraph", "parallel", "parameter", "pardon", "parent",
        "parity", "part", "participant", "participation", "particle", "particular", "partner",
        "partnership", "party", "pass", "passage", "passion", "past", "patch", "patent", "path",
        "patience", "patient", "patriotism", "pattern", "pause", "payment", "peace", "peak", "penalty",
        "pension", "percentage", "perception", "performance", "period", "permission", "persistence",
        "person", "personality", "perspective", "persuasion", "phenomenon", "philosophy", "phrase",
        "physics", "picture", "piece", "pillar", "pioneer", "pitch", "place", "plan", "planet",
        "platform", "play", "player", "plea", "pleasure", "plenty", "plot", "pocket", "poem", "poet",
        "poetry", "point", "poise", "poison", "policy", "politeness", "politics", "pollution",
        "popularity", "population", "portfolio", "portion", "position", "possession", "possibility",
        "post", "potential", "poverty", "powder", "power", "practice", "pragmatism", "praise",
        "precedent", "precision", "predication", "prediction", "preference", "prejudice", "premise",
        "premium", "preparation", "presence", "present", "presentation", "preservation", "presidency",
        "pressure", "prestige", "pretext", "prevalence", "prevention", "price", "pride", "primary",
        "principle", "print", "priority", "privacy", "privilege", "prize", "probability", "problem",
        "procedure", "process", "procession", "proclamation", "production", "productivity", "profession",
        "professional", "professor", "profile", "profit", "profitability", "program", "progress",
        "progression", "prohibition", "project", "projection", "promise", "promotion", "proof",
        "propaganda", "property", "proportion", "proposal", "proposition", "proprietor", "prosperity",
        "protection", "protest", "protocol", "provision", "provocation", "proximity", "psychology",
        "publicity", "publishing", "pulse", "punctuation", "punishment", "purchase", "purity", "purpose",
        "pursuit", "puzzle", "qualification", "quality", "quantity", "quarrel", "quarter", "quartet",
        "query", "quest", "question", "queue", "quiet", "quietness", "quota", "quotation", "race",
        "radiation", "rage", "raid", "rally", "range", "rank", "rate", "rating", "ratio", "rationality",
        "reach", "reaction", "reading", "reality", "realm", "reason", "reasoning", "rebel", "rebellion",
        "rebound", "recall", "reception", "receptivity", "recess", "recession", "recipe", "recipient",
        "recognition", "recollection", "recommendation", "reconciliation", "record", "recovery",
        "recreation", "recruitment", "recurrence", "redemption", "reduction", "redundancy", "reference",
        "referendum", "reflection", "reform", "refuge", "refusal", "regard", "regime", "region",
        "registration", "regret", "regulation", "rehabilitation", "rehearsal", "reign", "rejection",
        "relation", "relationship", "relaxation", "release", "relevance", "reliability", "relief",
        "religion", "reluctance", "remainder", "remark", "remedy", "reminder", "removal", "renaissance",
        "renewal", "renovation", "repair", "repetition", "replacement", "reply", "report", "representation",
        "repression", "reproduction", "republic", "reputation", "request", "requirement", "rescue",
        "research", "resemblance", "reservation", "reserve", "residence", "resident", "residue",
        "resignation", "resistance", "resolution", "resolve", "resort", "resource", "respect", "respite",
        "response", "responsibility", "rest", "restoration", "restraint", "restriction", "result",
        "resumption", "retention", "retreat", "return", "reunion", "revelation", "revenge", "revenue",
        "reversal", "reverse", "review", "revision", "revival", "revolution", "reward", "rhetoric",
        "rhythm", "riches", "riddle", "ride", "right", "righteousness", "rigidity", "rigor", "ring",
        "rise", "risk", "ritual", "rivalry", "road", "robbery", "rock", "role", "romance", "room",
        "root", "rotation", "route", "routine", "row", "royalty", "ruin", "rule", "ruling", "rumor",
        "rush", "sabotage", "sacrifice", "sadness", "safeguard", "safety", "saga", "sake", "salary",
        "sale", "salon", "salvation", "sample", "sanction", "sanctuary", "satisfaction", "saving",
        "scale", "scandal", "scenario", "scene", "schedule", "scheme", "scholarship", "school",
        "science", "scope", "score", "scorn", "scramble", "screening", "script", "scrutiny", "search",
        "season", "seat", "secession", "seclusion", "second", "secret", "secretary", "section",
        "sector", "security", "sediment", "seduction", "seed", "segment", "segregation", "selection",
        "self", "semblance", "semester", "senate", "senior", "sensation", "sense", "sensibility",
        "sensitivity", "sentiment", "separation", "sequence", "series", "sermon", "servant", "service",
        "session", "set", "setting", "settlement", "severity", "sex", "shade", "shadow", "shame",
        "shape", "share", "sheet", "shelter", "shift", "shock", "shore", "shortage", "shot", "show",
        "shower", "shrug", "side", "sight", "sign", "signal", "significance", "silence", "silver",
        "similarity", "simplicity", "simulation", "sin", "sincerity", "singer", "single", "site",
        "situation", "size", "skepticism", "skill", "skin", "slant", "slaughter", "sleep", "slice",
        "slide", "slip", "slogan", "slot", "slowdown", "smash", "smell", "smile", "smoke", "snapshot",
        "sneak", "snow", "society", "sociology", "software", "soil", "solitude", "solution", "sorrow",
        "soul", "sound", "soup", "source", "south", "sovereignty", "space", "span", "speaker",
        "specialist", "specialty", "species", "spectacle", "spectrum", "speculation", "speech", "speed",
        "spell", "spending", "sphere", "spirit", "spite", "split", "spokesman", "sponsor", "sport",
        "spot", "spread", "spring", "spy", "squad", "square", "stability", "staff", "stage", "stagnation",
        "stair", "stake", "stand", "standard", "standing", "star", "start", "state", "statement",
        "station", "statistics", "status", "statute", "stay", "steadiness", "steam", "steel", "stem",
        "step", "stereotype", "steward", "stick", "stimulus", "stock", "stone", "stop", "storage",
        "store", "storm", "story", "strain", "stranger", "strategy", "streak", "stream", "strength",
        "stress", "stretch", "strike", "string", "strip", "stroke", "structure", "struggle", "student",
        "studio", "study", "stuff", "style", "subject", "submission", "substance", "substitute",
        "subtlety", "success", "succession", "successor", "suffering", "sufficiency", "sugar",
        "suggestion", "suicide", "suit", "summary", "summer", "summit", "sun", "superior", "supervision",
        "supervisor", "supplement", "supply", "support", "surface", "surgery", "surplus", "surprise",
        "surrender", "surroundings", "surveillance", "survey", "survival", "survivor", "susceptibility",
        "suspense", "suspicion", "sustenance", "sweat", "swing", "switch", "sword", "symbol",
        "symmetry", "sympathy", "symptom", "syndrome", "synthesis", "system", "table", "tactic",
        "tag", "tail", "tale", "talk", "tank", "tap", "target", "tariff", "task", "taste", "tax",
        "teaching", "team", "tear", "technique", "technology", "teenager", "telecommunication",
        "telephone", "telescope", "television", "temper", "temperament", "temple", "tempo", "tendency",
        "tender", "tennis", "tension", "tent", "term", "terminal", "termination", "terms", "terrace",
        "territory", "terror", "terrorism", "test", "testimony", "testing", "text", "texture", "thanks",
        "theft", "theme", "theory", "therapy", "thesis", "thing", "thinking", "third", "thought",
        "threat", "threshold", "thrill", "throat", "throne", "thrust", "thumb", "ticket", "tide",
        "tie", "timber", "time", "timing", "tip", "tissue", "title", "toast", "today", "toe",
        "tolerance", "toll", "tomorrow", "tone", "tongue", "tool", "tooth", "top", "topic", "torch",
        "torment", "torture", "total", "touch", "tour", "tournament", "tower", "town", "trace",
        "track", "trade", "tradition", "traffic", "tragedy", "trail", "train", "training", "trait",
        "transaction", "transcript", "transfer", "transformation", "transit", "transition", "translation",
        "transmission", "transport", "trap", "trauma", "travel", "traveler", "treasure", "treasury",
        "treatment", "treaty", "tree", "trend", "trial", "triangle", "tribe", "tribute", "trick",
        "trip", "triumph", "trophy", "trouble", "truck", "trust", "truth", "try", "tube", "tumor",
        "tune", "tunnel", "turn", "turnover", "tutor", "twin", "twist", "type", "uncertainty",
        "unconscious", "understanding", "undertaking", "unemployment", "uniformity", "union", "unit",
        "unity", "universe", "university", "unrest", "update", "upgrade", "upset", "urgency", "usage",
        "use", "user", "utility", "utopia", "utterance", "vacation", "vacuum", "validity", "valley",
        "value", "vandalism", "vanity", "variable", "variant", "variation", "variety", "vector",
        "vegetable", "vehicle", "velocity", "velvet", "vendor", "venture", "venue", "verb", "verdict",
        "verification", "version", "vessel", "veteran", "veto", "vicinity", "victim", "victory",
        "video", "view", "vigilance", "vigor", "village", "villain", "violation", "violence", "virtue",
        "virus", "visibility", "vision", "visit", "visitor", "visual", "vitamin", "vocabulary", "vogue",
        "voice", "void", "volatility", "volcano", "volume", "volunteer", "vote", "voter", "voting",
        "vow", "voyage", "vulnerability", "wager", "wage", "waiting", "waiver", "wake", "walk",
        "wall", "wandering", "want", "war", "ward", "wardrobe", "warehouse", "warfare", "warmth",
        "warning", "warrant", "warranty", "warrior", "waste", "watch", "water", "wave", "way",
        "weakness", "wealth", "weapon", "weather", "web", "wedding", "weed", "week", "weekend",
        "weight", "welcome", "welfare", "well-being", "west", "wheel", "whim", "whisper", "whole",
        "width", "wife", "wilderness", "will", "willingness", "win", "wind", "window", "wine",
        "wing", "winner", "winter", "wisdom", "wish", "withdrawal", "witness", "woman", "wonder",
        "wood", "word", "work", "worker", "workforce", "working", "world", "worm", "worry", "worship",
        "worth", "wound", "wreck", "writing", "wrong", "yard", "year", "yield", "youth", "zeal",
        "zest", "zone"
    ];



    public string GenerateInitialUserName()
    {
        var userName = GetNewName();
        _userNameActivityOverview.TryAdd(userName, 0);
        _userNameAndDisplayNameOverview.TryAdd(userName, userName);
        return userName;
    }

    public string GetNewName()
    {
        var adj = _adjectives[Random.Shared.Next(_adjectives.Length)];
        var subj = _nouns[Random.Shared.Next(_nouns.Length)];
        return $"{char.ToUpper(adj[0])}{adj[1..]} {char.ToUpper(subj[0])}{subj[1..]}";
    }

    public int MessageCount(string userName)
    {
        _userNameActivityOverview.TryGetValue(userName, out var count);
        return count;
    }

    public void NameActive(string userName)
    {
       if (_userNameActivityOverview.TryGetValue(userName, out var count)) _userNameActivityOverview[userName] = ++count;
    }

    public string RerollName(string displayName)
    {
        if (!_userNameAndDisplayNameOverview.TryRemove(displayName, out var userName) || _userNameActivityOverview[userName] > 1) return displayName;
        string newDisplayName;
        do
        {
            newDisplayName = GetNewName();
        } while (_userNameAndDisplayNameOverview.ContainsKey(newDisplayName));
        _userNameAndDisplayNameOverview.TryAdd(newDisplayName, userName);
        return newDisplayName;
    }
}
